import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { ARTICLE_THEME_SCRIPT } from "../lib/publications/contract";
import { inspectArticle, verifyPublications } from "../lib/publications/verify";
import { FixtureRepo, fixtureArticle } from "./helpers/bundle";
import { sshSign } from "./helpers/sign";

// Every bundle here is a FIXTURE, signed with a throwaway key generated by the test.
const run = (repo: FixtureRepo, allowFixtureMarker = true) =>
  verifyPublications({ root: repo.root, signers: repo.signers, allowFixtureMarker });
const errorsOf = (repo: FixtureRepo) => run(repo).errors.join("\n");

describe("publication bundle", () => {
  it("accepts a correctly signed, hashed and self-contained bundle", () => {
    const repo = new FixtureRepo();
    repo.add({ id: "GSP-0001" });
    const r = run(repo);
    expect(r.errors).toEqual([]);
    expect(r.active.map((b) => b.manifest.route)).toEqual(["/research/gs-fixture-article"]);
  });

  it("refuses everything while no publisher key is pinned (fail closed)", () => {
    const repo = new FixtureRepo();
    repo.add({ id: "GSP-0001" });
    expect(verifyPublications({ root: repo.root, signers: [], allowFixtureMarker: true }).errors.join()).toMatch(/no trusted publisher key/);
  });

  it("refuses a fixture under production rules: fixtures can never be published", () => {
    const repo = new FixtureRepo();
    repo.add({ id: "GSP-0001" });
    expect(run(repo, false).errors.join()).toMatch(/gs-fixture/);
  });

  it("refuses a bundle signed by a key that is not pinned", () => {
    const repo = new FixtureRepo();
    const stranger = new FixtureRepo();
    const dir = stranger.add({ id: "GSP-0001" });
    expect(verifyPublications({ root: stranger.root, signers: repo.signers, allowFixtureMarker: true }).errors.join()).toMatch(/not the pinned/);
    expect(dir).toBeTruthy();
  });

  it("refuses an article changed after signing — one byte is enough", () => {
    const repo = new FixtureRepo();
    const dir = repo.add({ id: "GSP-0001" });
    const html = readFileSync(join(dir, "article.html"));
    html[html.length - 2] = html[html.length - 2] ^ 1;
    writeFileSync(join(dir, "article.html"), html);
    expect(errorsOf(repo)).toMatch(/sha256 differs/);
  });

  it("refuses a manifest changed after signing", () => {
    const repo = new FixtureRepo();
    const dir = repo.add({ id: "GSP-0001" });
    const path = join(dir, "manifest.json");
    writeFileSync(path, readFileSync(path, "utf8").replace("GS-FIXTURE article", "GS-FIXTURE articlf"));
    expect(errorsOf(repo)).toMatch(/signature does not verify/);
  });

  it("refuses a wrong self-hash, even when correctly signed", () => {
    const repo = new FixtureRepo();
    const dir = repo.add({ id: "GSP-0001" });
    const m = JSON.parse(readFileSync(join(dir, "manifest.json"), "utf8"));
    m.manifest_sha256 = "f".repeat(64);
    const bytes = Buffer.from(JSON.stringify(m, null, 2) + "\n");
    writeFileSync(join(dir, "manifest.json"), bytes);
    writeFileSync(join(dir, "manifest.json.sig"), sshSign(repo.key, bytes, "ground-state.web-publication.v1"));
    expect(errorsOf(repo)).toMatch(/manifest_sha256 does not match/);
  });

  it("refuses an unlisted extra file, a missing signature and a nested directory", () => {
    const a = new FixtureRepo();
    appendFileSync(join(a.add({ id: "GSP-0001" }), "notes.txt"), "x");
    expect(errorsOf(a)).toMatch(/notes\.txt is not listed/);

    const b = new FixtureRepo();
    const dir = b.add({ id: "GSP-0001" });
    writeFileSync(join(dir, "manifest.json.sig"), "");
    expect(errorsOf(b)).toMatch(/signature/);
  });

  it("refuses schema violations: unknown fields, bad ids, mismatched directory and route", () => {
    const unknown = new FixtureRepo();
    unknown.add({ id: "GSP-0001", edit: (m) => (m.internal_path = "/somewhere") });
    expect(errorsOf(unknown)).toMatch(/schema: .*additional properties/);

    const badId = new FixtureRepo();
    badId.add({ id: "GSP-0001", edit: (m) => (m.publication_id = "GSER-0001") });
    expect(errorsOf(badId)).toMatch(/schema/);

    const dirMismatch = new FixtureRepo();
    dirMismatch.add({ id: "GSP-0001", edit: (m) => (m.publication_id = "GSP-0002") });
    expect(errorsOf(dirMismatch)).toMatch(/directory name and publication_id differ/);

    const route = new FixtureRepo();
    route.add({ id: "GSP-0001", edit: (m) => (m.route = "/research/elsewhere") });
    expect(errorsOf(route)).toMatch(/route must be \/research\/<slug>/);
  });

  it("refuses an article that is not the approved article", () => {
    const repo = new FixtureRepo();
    repo.add({ id: "GSP-0001", edit: (m) => ((m.bindings as Record<string, string>).approved_article_sha256 = "a".repeat(64)) });
    expect(errorsOf(repo)).toMatch(/not the approved article/);
  });
});

describe("article content", () => {
  const route = "/research/gs-fixture-article";
  const page = (extra: string) => Buffer.from(fixtureArticle(route, extra));
  const problems = (extra: string) => inspectArticle(page(extra), route, true).join("\n");

  it("passes a self-contained page", () => {
    expect(inspectArticle(page("Plain text."), route, true)).toEqual([]);
  });

  it.each([
    ["Draft for human content and visual review. Not authorised for publication.", /review-render footer/],
    ["Record GSER-0001", /internal evidence-record identifier/],
    ["Report GS-TER-0001", /internal technical-report identifier/],
    ["job GSFB-v1-20260930", /internal job identifier/],
    ['<span data-visual-revision="001"></span>', /review workflow marker/],
    ["sha256 c710e7e2", /hash or approval metadata/],
    ["/Users/aisystem/AI-System", /local filesystem path/],
    ["<script>alert(1)</script>", /<script>/],
    ['<iframe src="https://example.org"></iframe>', /<iframe>/],
    ['<img src="https://example.org/x.png" alt="">', /external resource/],
    ['<div style="background:url(https://example.org/x.png)"></div>', /external url\(\)/],
    ['<a href="#" onclick="x()">x</a>', /inline event handler/],
    ['<meta name="robots" content="noindex">', /noindex/],
    ['<link rel="stylesheet" href="https://example.org/x.css">', /no <link> other than rel=canonical/],
  ])("refuses %s", (extra, why) => {
    expect(problems(extra)).toMatch(why);
  });

  it("accepts the pinned theme script, once, byte for byte", () => {
    expect(problems(`<script>${ARTICLE_THEME_SCRIPT}</script>`)).toBe("");
  });

  it.each([
    ["changed by one byte", `<script>${ARTICLE_THEME_SCRIPT.replace("gs-theme", "gs-themf")}</script>`, /<script>/],
    ["with an attribute", `<script type="module">${ARTICLE_THEME_SCRIPT}</script>`, /<script>/],
    ["beside another script", `<script>${ARTICLE_THEME_SCRIPT}</script><script>alert(1)</script>`, /<script>/],
    ["twice", `<script>${ARTICLE_THEME_SCRIPT}</script><script>${ARTICLE_THEME_SCRIPT}</script>`, /more than once/],
  ])("refuses the theme script %s", (_, extra, why) => {
    expect(problems(extra)).toMatch(why);
  });

  it("accepts inline data: resources", () => {
    expect(problems('<img src="data:image/png;base64,AAAA" alt="">')).toBe("");
  });

  it("requires exactly one canonical link, to this route on the production origin", () => {
    const wrong = Buffer.from(fixtureArticle("/research/other"));
    expect(inspectArticle(wrong, route, true).join()).toMatch(/canonical link must be https:\/\/groundstatemethod\.com\/research\/gs-fixture-article/);
    const none = Buffer.from(fixtureArticle(route).replace(/<link rel="canonical"[^>]*>\n/, ""));
    expect(inspectArticle(none, route, true).join()).toMatch(/exactly one <link rel="canonical">/);
  });

  it("refuses invalid UTF-8 and a missing doctype", () => {
    expect(inspectArticle(Buffer.from([0x3c, 0xff, 0xfe]), route, true).join()).toMatch(/UTF-8/);
    expect(inspectArticle(Buffer.from(fixtureArticle(route).replace("<!doctype html>", "")), route, true).join()).toMatch(/doctype/);
  });
});

describe("supersession and withdrawal", () => {
  it("serves the newest version of a route", () => {
    const repo = new FixtureRepo();
    repo.add({ id: "GSP-0001" });
    repo.add({ id: "GSP-0002", supersedes: "GSP-0001", title: "GS-FIXTURE article, version 2" });
    const r = run(repo);
    expect(r.errors).toEqual([]);
    expect(r.active.map((b) => b.id)).toEqual(["GSP-0002"]);
  });

  it("refuses a new version that moves the route", () => {
    const repo = new FixtureRepo();
    repo.add({ id: "GSP-0001" });
    repo.add({ id: "GSP-0002", supersedes: "GSP-0001", slug: "gs-fixture-moved" });
    expect(errorsOf(repo)).toMatch(/changes the route of GSP-0001/);
  });

  it("refuses two bundles superseding the same one, and a missing predecessor", () => {
    const twice = new FixtureRepo();
    twice.add({ id: "GSP-0001" });
    twice.add({ id: "GSP-0002", supersedes: "GSP-0001" });
    twice.add({ id: "GSP-0003", supersedes: "GSP-0001" });
    expect(errorsOf(twice)).toMatch(/superseded twice/);

    const missing = new FixtureRepo();
    missing.add({ id: "GSP-0002", supersedes: "GSP-0001" });
    expect(errorsOf(missing)).toMatch(/supersedes GSP-0001, which is not here/);
  });

  it("refuses two independent bundles on one route", () => {
    const repo = new FixtureRepo();
    repo.add({ id: "GSP-0001" });
    repo.add({ id: "GSP-0002" });
    expect(errorsOf(repo)).toMatch(/claimed by GSP-0001 and GSP-0002/);
  });

  it("withdraws a route: nothing served, the withdrawal recorded", () => {
    const repo = new FixtureRepo();
    repo.add({ id: "GSP-0001" });
    repo.add({ id: "GSP-0002", action: "WITHDRAW", supersedes: "GSP-0001" });
    const r = run(repo);
    expect(r.errors).toEqual([]);
    expect(r.active).toEqual([]);
    expect(r.withdrawn.map((b) => b.id)).toEqual(["GSP-0002"]);
  });

  it("refuses a withdrawal that withdraws nothing", () => {
    const repo = new FixtureRepo();
    repo.add({ id: "GSP-0001", action: "WITHDRAW" });
    expect(errorsOf(repo)).toMatch(/schema/);
  });
});
