import type { MetadataRoute } from "next";

// Emitted as a static file by `output: "export"`.
export const dynamic = "force-static";
import { absoluteUrl, siteUrlConfigured } from "@/site.config";

/**
 * robots.txt. Generated by Next into the static export at build time.
 *
 * Until the production origin is configured the whole site is disallowed: a
 * crawler that finds a preview deployment before launch will index the empty
 * state and the wrong host. `npm run preflight` fails a production build in that
 * case, so this is a second line of defence rather than the plan.
 */
export default function robots(): MetadataRoute.Robots {
  if (!siteUrlConfigured) {
    return { rules: { userAgent: "*", disallow: "/" } };
  }
  return {
    rules: { userAgent: "*", allow: "/", disallow: "/styleguide" },
    sitemap: absoluteUrl("/sitemap.xml"),
  };
}
