import type { MetadataRoute } from "next";

// Emitted as a static file by `output: "export"`.
export const dynamic = "force-static";
import { publishedArticles } from "@/lib/publications";
import { publishedJournal } from "@/content/journal";
import { STATIC_ROUTES, absoluteUrl, siteUrlConfigured } from "@/site.config";

/**
 * sitemap.xml. Generated by Next into the static export at build time.
 *
 * A sitemap needs absolute URLs, so it is empty until the origin is configured
 * rather than emitting relative or guessed ones. `/styleguide` is internal and
 * noindex, and is never listed.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  if (!siteUrlConfigured) return [];

  const now = new Date();
  return [
    ...STATIC_ROUTES.map((p) => ({ url: absoluteUrl(p)!, lastModified: now })),
    ...publishedArticles().map((p) => ({
      url: absoluteUrl(p.route)!,
      lastModified: new Date(p.publishedOn),
    })),
    ...publishedJournal().map((e) => ({
      url: absoluteUrl(`/journal/${e.slug}`)!,
      lastModified: new Date(e.date),
    })),
  ];
}
